name: Pull Request
on:
  push:
    branches: [ master ]
jobs:
  build:
    environment: ci
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1
      - uses: joschi/setup-jdk@v1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        with:
          java-version: 8
      - run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 10
          sudo apt-get install -y ocl-icd-opencl-dev clang-10 lldb-10 lld-10 clangd-10
      - run: mvn --settings .mvn/settings.xml -Dgpg.passphrase=${{ secrets.GPG_KEY_PASSPHRASE }} clean javadoc:jar deploy -P notest -P signed
